---
# http://blog.strug.de/2012/06/my-homebrew-multi-user-setup/
- name: Homebrew | Create brew group
  group:
    name: brew
    state: present
    system: no
  become: true

- name: Homebrew | Use group permissions for homebrew /usr/local
  file: >
    path=/usr/local
    group=brew
    mode="g+w"
  become: true

#- name: Homebrew | Use group permissions for homebrew /Library/Caches/Homebrew
#  file: >
#    path=/Library/Caches/Homebrew
#    group=brew
#    mode="g+w"
#  become: true

- name: Homebrew | Use group permissions for homebrew /opt/homebrew-cask/Caskroom
  file: >
    path=/usr/local/Caskroom
    owner=root
    group=admin
    mode="g+w"
    recurse=yes
  become: true

# sudo chown -R root:admin /opt/homebrew-cask/Caskroom/yasu
# sudo chmod -R g+w /opt/homebrew-cask/Caskroom/yasu
