---
# This playbook contains common plays that will be run on all nodes.
- name: Oh-My-Zsh | Install 
  git: >
    repo={{ package.oh_my_zsh.origin.src }}
    dest={{ package.oh_my_zsh.origin.dest }}
    update=yes
    accept_hostkey=yes

- name: Oh-My-Zsh | Switch to ZSH
  shell: chsh -s /bin/zsh
  sudo: true

# - name: Oh-My-Zsh | Copy RC configuration
#   copy: >
#     src=zshrc
#     dest=~/.zshrc
#     mode=0644

# - name: Oh-My-Zsh | Add github rate limit token
#   lineinfile: >
#     dest=~/.zshrc
#     regexp='^#export HOMEBREW_GITHUB_API_TOKEN='
#     insertafter='^#export HOMEBREW_GITHUB_API_TOKEN='
#     line="export HOMEBREW_GITHUB_API_TOKEN={{ lookup('file', files.github_rate_limit_token) }}"

- name: Oh-My-Zsh | Copy aliases configuration
  copy: >
    src=zsh-aliases
    dest=~/.zsh-aliases
    mode=0644
