---
# https://ruigomes.me/blog/perfect-iterm-osx-terminal-installation/
- name: Oh-My-Zsh | Download PowerLine fonts
  git: >
    repo={{ package.powerline.origin.src }}
    dest={{ package.powerline.origin.dest }}
    update=yes
    accept_hostkey=yes

- name: Oh-My-Zsh | Install PowerLine fonts
  shell: cd {{ package.powerline.origin.dest }} && ./install.sh
  become: false

- name: Oh-My-Zsh | Reset font cache
  shell: atsutil databases -remove
  become: true
