---
- name: Get the username running the deploy
  local_action: command whoami
  register: username_on_the_host

- name: Get the name of the machine
  local_action: command hostname
  register: hostname
#- debug: var=username_on_the_host
