---
- name: Sys Config | System
  shell: "{{ item }}"
  with_items: 
   - "{{ osx_config_sys.system }}"
  become: true

- name: Sys Config | System SSD Tweaks
  shell: "{{ item }}"
  with_items: 
   - "{{ osx_config_sys.system_ssd_tweaks }}"
  become: true
